spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
  docker:
    compose:
      enabled: false
  cache:
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
  jpa:
    open-in-view: false