spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  docker:
    compose:
      enabled: false
  cache:
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s