spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
  docker:
    compose:
      enabled: false
  jpa:
    open-in-view: false

# for redis cache and session
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      username: ${REDIS_USER}
      password: ${REDIS_PASS}
      port: ${REDIS_PORT}
      ssl:
        enabled: true
      repositories:
        enabled: false
  threads:
    virtual:
      enabled: true

# fro compression
server:
  port: ${PORT:8080}
  compression:
    enabled: true
    mime-types: text/css,text/html,text/javascript,application/json