spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
  docker:
    compose:
      enabled: false

  # for redis cache and session
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      username: ${REDIS_USER}
      password: ${REDIS_PASS}
      port: ${REDIS_PORT}
      ssl:
        enabled: true
      repositories:
        enabled: false
  threads:
    virtual:
      enabled: true

# fro compression
server:
  compression:
    enabled: true
    mime-types: text/css,text/html,text/javascript,application/json

management:
  datadog:
    metrics:
      export:
        api-key: ${DATADOG_API_KEY}
        application-key: ${DATADOG_APP_KEY}
        uri: ${DATADOG_URI}
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 0.5
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST}:${ZIPKIN_PORT}/api/v2/spans

