spring:
  jpa:
    show-sql: true

  cache:
    #    caffeine:
    #      spec: maximumSize=500,expireAfterAccess=600s
    type: redis
  data:
    redis:
      repositories:
        enabled: false
management:
  datadog:
    metrics:
      export:
        enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0