spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
  docker:
    compose:
      enabled: false
  cache:
    type: redis
  jpa:
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      username: ${REDIS_USER}
      password: ${REDIS_PASS}
      port: ${REDIS_PORT}
      database: 0
